### PR TITLE
Py3.11 compatibility

### LINKED ISSUE #13: Python 3.11 incompatibility ( async coroutines removed )
I was trying to use this integration in the latest Home Assistant release (2023.6) and encountered this error:

> 2023-06-08 17:10:32 home-assistant  | 2023-06-08 17:10:32.772 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform homeassistant.components.russound_rio.media_player
> 2023-06-08 17:10:32 home-assistant  | Traceback (most recent call last):
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
> 2023-06-08 17:10:32 home-assistant  |     cache[full_name] = self._import_platform(platform_name)
> 2023-06-08 17:10:32 home-assistant  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
> 2023-06-08 17:10:32 home-assistant  |     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
> 2023-06-08 17:10:32 home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
> 2023-06-08 17:10:32 home-assistant  |     return _bootstrap._gcd_import(name[level:], package, level)
> 2023-06-08 17:10:32 home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2023-06-08 17:10:32 home-assistant  |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
> 2023-06-08 17:10:32 home-assistant  |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
> 2023-06-08 17:10:32 home-assistant  |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
> 2023-06-08 17:10:32 home-assistant  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
> 2023-06-08 17:10:32 home-assistant  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
> 2023-06-08 17:10:32 home-assistant  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/russound_rio/media_player.py", line 4, in <module>
> 2023-06-08 17:10:32 home-assistant  |     from russound_rio import Russound
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/local/lib/python3.11/site-packages/russound_rio/__init__.py", line 1, in <module>
> 2023-06-08 17:10:32 home-assistant  |     from .rio import (
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/local/lib/python3.11/site-packages/russound_rio/rio.py", line 59, in <module>
> 2023-06-08 17:10:32 home-assistant  |     class Russound:
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/local/lib/python3.11/site-packages/russound_rio/rio.py", line 157, in Russound
> 2023-06-08 17:10:32 home-assistant  |     @asyncio.coroutine
> 2023-06-08 17:10:32 home-assistant  |      ^^^^^^^^^^^^^^^^^
> 2023-06-08 17:10:32 home-assistant  | AttributeError: module 'asyncio' has no attribute 'coroutine'

This appears to be an incompatibility with async semantics in Python 3.11: https://stackoverflow.com/questions/74345065/attributeerror-module-asyncio-has-no-attribute-coroutine-in-python-3-11

### PR DESCRIPTION
**Pull request by chphilli**
Simple update to fix #13 ( and ultimately, https://github.com/home-assistant/core/issues/94295 ). 

This change:
   - adds Python 3.11 as a target for building, testing, and packaging
   - changes the rio.py & examples/basic.py usage of `@asyncio.coroutines` to `async def` ( and associated `yield`s to `await`s )
   - adds a basic `devcontainer.json` to make building/testing easier
   - bumps the package version to 1.9 (I think that's the right way to do this?)

The basic.py script successfully listed the zones and sources on my local Russound device, so I think this is working as intended.

### CODE REVIEW

**Comment by chphilli** [comment]
@wickerwaka -- rumor is that you're not actively working on this, but I'm hoping you can still take a look and help get this into the PyPI package so this can work with the 2023.6 home assistant release. Thanks!

**Comment by chphilli** [comment]
@wickerwaka in the name of complete transparency, I wanted to let you know that I've [filed a request with PyPI](https://github.com/pypi/support/issues/2924) to take over the russound-rio package as abandoned.

I sincerely appreciate the work you've done so far to provide this library, and I genuinely hope that you aren't offended or upset by the request. I just want to be able to get the fix published for other folks that are relying on the package you've put together. If you're interested in continuing maintenance on the project, just let me know and I'll happily withdraw the application. 

Thanks again for putting this together! It's a joy to be able to control my Russound from Home Assistant and I wouldn't have been able to do it without you paving the way!

**Comment by chphilli** [comment]
This will be merged in chphilli/russound_rio rather than here. Thanks @wickerwaka!

**Comment by vm2700** [comment]
While you're at it, can you also please fix: https://github.com/home-assistant/core/issues/68332
I hit it all the time.

Leaving the same comment at: https://github.com/home-assistant/core/issues/94295
